from flask import Flask, render_template, request, jsonify
from flask_cors import CORS
import os
import tempfile
import io


app = Flask(__name__)
CORS(app)


@app.route('/')
def index():
    return render_template('index.html')


# Create a global variable to store the index
index = None


@app.route('/upload', methods=['POST'])
def upload():
    global index
    if request.method == 'POST':
        # Get the files from the request
        files = request.files.getlist('files[]')
        # Create a temporary directory to store the files
        with tempfile.TemporaryDirectory() as temp_dir:
            for file in files:
                file_path = os.path.join(temp_dir, file.filename)
                file.save(file_path)
        # TODO: Implement a function that constructs a JSON index using the uploaded files
        #     The function takes in a directory path (str)
        #     and saves a file called 'index.json' to the current working directory.
        return jsonify({'status': 'success'})


@app.route('/query', methods=['POST'])
def process_query():
    # global index
    #
    # if not index:
    #     return jsonify({'status': 'error', 'message': 'No index available. Please upload files first.'})
    # TODO: Implement a function to answer questions.
    #     This function takes in a question (str) and
    #     returns an answer generated by the ChatGPT API.
    return jsonify({'status': 'success', 'response': "Success"})


if __name__ == '__main__':
    app.run(debug=True)
